// import { ExperienceSectionType } from '@/lib/types/sections'

// export const experienceSection: ExperienceSectionType = {
//     title: "where i've worked",
//     experiences: [
//         {
//             company: 'NextNoor - (Full Time)',
//             companyUrl: 'https://nexnoor.com/',
//             role: 'Junior Full Stack Enginner',
//             started: 'Jun 2024',
//             upto: 'Present',
//             tasks: [
//                 'Job Description:',
//                 'Worked as a junior developer in a team of 1-5 developers.',
//                 'Technologies used:',
//                 'React Js, React-native, Nativebase, Material Ui, Mantine Ui, EditorJS, Yopta-Editor, BlockNoteJS, Redux, Typescript, HTML5, SCSS, CSS3, PSD to HTML, Slack, Trello, Jira Software, Jira Board, Jira Application, Gitlab, Github, Skype, Zoom, Google Meet, Google Hangout, Figma/PSD to Nextjs, Figma/PSD to Reactjs, Figma/PSD to Reactnative, Figma/PSD to Html/CSS',
//             ],
//         },
//         {
//             company: 'Propmotive',
//             companyUrl: 'https://propmotive.com/',
//             role: 'Junior Full Stack Enginner',
//             started: 'Jun 2023',
//             upto: 'Aug 2023',
//             tasks: [
//                 'Job Description:',
//                 'Worked as a junior developer in a team of 1-5 developers.',
//                 'Technologies used:',
//                 'React Js, Material Ui, Mantine Ui, EditorJS, Yopta-Editor, BlockNoteJS, Redux, Typescript, HTML5, SCSS, CSS3, PSD to HTML, Slack, Trello, Jira Software, Jira Board, Jira Application, Gitlab, Github, Skype, Zoom, Google Meet, Google Hangout, Figma/PSD to Nextjs, Figma/PSD to Reactjs, Figma/PSD to Reactnative, Figma/PSD to Html/CSS',
//             ],
//         },
//         {
//             company: 'Propmotive',
//             companyUrl: 'https://propmotive.com/',
//             role: 'Junior Full-stack Developer',
//             started: 'March 2023',
//             upto: 'Jun 2023',
//             tasks: [
//                 'Job Description:',
//                 'Worked as a junior developer in a team of 1-5 developers.',
//                 'Technologies used:',
//                 'React Js, Material Ui, Mantine Ui, EditorJS, Yopta-Editor, BlockNoteJS, Redux, Typescript, HTML5, SCSS, CSS3, PSD to HTML, Slack, Trello, Jira Software, Jira Board, Jira Application, Gitlab, Github, Skype, Zoom, Google Meet, Google Hangout, Figma/PSD to Nextjs, Figma/PSD to Reactjs, Figma/PSD to Reactnative, Figma/PSD to Html/CSS',
//             ],
//         },
//         {
//             company: 'Propmotive',
//             companyUrl: 'https://propmotive.com/',
//             role: 'Junior Front End Developer',
//             started: 'Apr 2021',
//             upto: 'Jan 2022',
//             tasks: [
//                 'Job Description:',
//                 'Worked on an application that was providing an online shoping platform.',
//                 'Worked as a junior developer in a team of 1-5 developers.',
//                 'Technologies used:',
//                 'React Js, Material Ui, HTML5, SCSS, CSS3, PSD to HTML, Slack, Trello, Jira Software, Jira Board, Jira Application, Gitlab, Github, Skype, Zoom, Google Meet, Google Hangout, Firebase'
//             ],
//         },
//         {
//             company: 'Queno (Private) Limited',
//             companyUrl: 'https://www.linkedin.com/company/the-queno/',
//             role: 'Junior Front End Developer',
//             started: 'May 2020',
//             upto: 'May 2021',
//             tasks: [
//                 'Job Description:',
//                 'Worked on an application that was providing an Educational platform.',
//                 'Worked  as a junior developer in a team of 8-10 developers.',
//                 'Technologies used:',
//                 ' Angular 9, Angular Material, HTML5, SCSS, CSS3, Swagger Api, PSD to HTML, Slack, Trello, Jira Software,  Jira Board, Jira Application, Gitlab, Github, Skype, Zoom, Google Meet, Google Hangout, Firebase',
//             ],
//         },
//     ],
// };


import { ExperienceSectionType } from '@/lib/types/sections'

export const experienceSection: ExperienceSectionType = {
    title: "Where I've Worked",
    experiences: [
        {
            company: 'Awwcor Inc (Remote)',
            companyUrl: '',
            role: 'Senior JavaScript Developer',
            started: 'Sep 2021',
            upto: 'May 2023',
            tasks: [
                'Job Description:',
                'Worked on a large clinical industry application (NDA signed).',
                'Developed backend APIs using NestJS on top of Node.js.',
                'Implemented unit testing using Jest.',
                'Integrated GraphQL-like implementation on the backend.',
                'Developed front-end modules using Angular 12.',
                'Technologies used:',
                'MEAN Stack, Angular 12, Node.js, NestJS, MySQL, Angular Material, SCSS, HTML5, RxJS, Jest, Agile Methodology.',
            ],
        },
        {
            company: 'Phaedra Solutions (Remote)',
            companyUrl: '',
            role: 'Technical Lead',
            started: 'Mar 2020',
            upto: 'Sep 2020',
            tasks: [
                'Job Description:',
                'Worked on an educational platform application.',
                'Led and assisted a team of 4-5 developers.',
                'Implemented end-to-end (E2E) testing using Cypress.',
                'Developed GraphQL API using Apollo on both frontend and backend.',
                'Set up and managed code deployment and build pipelines on Microsoft Azure Cloud.',
                'Technologies used:',
                'MEAN Stack, Angular 8, Node.js, Express.js, GraphQL, Apollo, MySQL, Sequelize, Docker, Angular Material, SCSS, HTML5, RxJS, Cypress, Agile Methodology, Microsoft Azure Cloud.',
            ],
        },
        {
            company: 'Tazteq PK',
            companyUrl: '',
            role: 'Lead Front-End Engineer',
            started: 'Jan 2019',
            upto: 'Nov 2019',
            tasks: [
                'Job Description:',
                'Developed an ERP system for an air ticketing platform.',
                'Led a team of 5 developers.',
                'Implemented Redux state management and designed custom state objects for lazily loaded routes.',
                'Developed a reporting module using Report.js as a microservice and converted JSON datasets to dynamic UI reports.',
                'Injected generated reports into the frontend and provided PDF export options.',
                'Technologies used:',
                'MEAN Stack, Angular 8, Node.js, Express.js, Report.js, Redux, Angular Material, SCSS, HTML5, RxJS, Agile Methodology, Jenkins, Jira.',
            ],
        },
        {
            company: 'DatumSquare IT Services (Remote)',
            companyUrl: '',
            role: 'Senior MEAN Stack Developer',
            started: 'Aug 2017',
            upto: 'Jan 2019',
            tasks: [
                'Job Description:',
                'Refactored and migrated a real estate business application from PHP to Angular 4+.',
                'Integrated JWT authentication on a Laravel platform.',
                'Developed admin module and integrated third-party services such as Auth0 SSO, Wistia, Skype, and Duda APIs.',
                'Created a Node.js-based thumbnail generator server for file previews.',
                'Worked remotely for 1950+ hours and received an award of excellence.',
                'Technologies used:',
                'Angular 4+, Node.js, Express.js, PostgreSQL, Node-Thumbnail, JWT, Bootstrap, HTML5, SCSS, SSO Integration, Wistia API, Duda API, Skype Integration.',
            ],
        },
        {
            company: 'TechApps Solutions (Karachi)',
            companyUrl: '',
            role: 'Senior MEAN Stack Developer',
            started: 'Dec 2016',
            upto: 'Aug 2017',
            tasks: [
                'Job Description:',
                'Mentored junior developers.',
                'Developed features for SkillCafe platform.',
                'Technologies used:',
                'AngularJS, Bootstrap, Highcharts, MongoDB, Express.js, Node.js, React Native, HTML5, SCSS, Angular Material, jQuery.',
            ],
        },
        {
            company: 'Matters App (Freelance, Remote)',
            companyUrl: '',
            role: 'Senior MEAN Stack Developer',
            started: 'Oct 2016',
            upto: 'Aug 2016',
            tasks: [
                'Job Description:',
                'Developed an email client that integrated Gmail, Outlook, and Yahoo into a single module using IMAP.',
                'Integrated Firebase for real-time messaging.',
                'Technologies used:',
                'AngularJS, Bootstrap, React.js, Firebase, IMAP Protocol, Express.js, Node.js, jQuery, HTML, CSS.',
            ],
        },
        {
            company: 'Fork Traders (Karachi)',
            companyUrl: '',
            role: 'Senior MEAN Stack Developer',
            started: 'Nov 2015',
            upto: 'Oct 2016',
            tasks: [
                'Job Description:',
                'Developed a fully configurable grid module similar to Microsoft Excel with advanced sorting and filtering features.',
                'Developed a regex generator for data virtualization and optimized a grid for handling over 2 million records.',
                'Migrated the system from AngularJS to Angular 4 and improved data query efficiency using MongoDB Aggregation Framework.',
                'Technologies used:',
                'AngularJS, Angular 4, Node.js, Express.js, MongoDB, Regex Generator, HTML, SCSS.',
            ],
        },
    ],
};
